name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  x86-64-unknown-linux-release:
    name: Build and upload x86-64-unknown-linux to Cloudsmith
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl-3.2.5:release
    steps:
      - uses: actions/checkout@v1
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-unknown-linux-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  x86-64-apple-darwin-release:
    name: Build and upload x86-64-apple-darwin to Cloudsmith
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install pony tools
        run:  bash .ci-scripts/macOS-install-release-pony-tools.bash
      - name: brew install dependencies
        run: brew install coreutils
      - name: pip install dependencies
        run: pip3 install --upgrade cloudsmith-cli
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-apple-darwin-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  build-release-docker-images:
    name: Build and push release Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-scripts/release/build-docker-images-on-release.bash

  update-latest-release-tag:
    name: Update latest-release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Tag
        run: |
          git tag --force latest-release
          git push --force "https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" latest-release
        env:
          TOKEN: ${{ secrets.RELEASE_TOKEN }}

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-release, x86-64-apple-darwin-release, build-release-docker-images, update-latest-release-tag]
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: docker://ponylang/release-bot-action:0.5.0
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
